name: 'Build JupyterLite'
description: 'Build JupyterLite from source'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup pip (base)
      shell: bash
      run: python3 -m pip install --user -U pip setuptools wheel

    - name: Cache (pip)
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: |
          ${{ env.CACHE_EPOCH }}-${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ env.CACHE_EPOCH }}-${{ runner.os }}-pip-

    - name: Setup pip (build)
      shell: bash
      run: python3 -m pip install -r requirements-build.txt

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Cache (node_modules)
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: node_modules/
        key: |
          ${{ env.CACHE_EPOCH }}-${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}

    - name: Cache (.yarn-packages)
      uses: actions/cache@v3
      id: cache-yarn-packages
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      with:
        path: .yarn-packages
        key: |
          ${{ env.CACHE_EPOCH }}-yarn-packages-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ env.CACHE_EPOCH }}-yarn-packages-

    # TODO: investigate fails observed in https://github.com/jupyterlite/jupyterlite/pull/746
    # - name: Cache (wepback)
    #   uses: actions/cache@v3
    #   with:
    #     path: build/webpack
    #     key: |
    #       ${{ env.CACHE_EPOCH }}-webpack-${{ hashFiles('yarn.lock') }}-${{ hashFiles('app/webpack.config.js') }}
    #     restore-keys: |
    #       ${{ env.CACHE_EPOCH }}-webpack-${{ hashFiles('yarn.lock') }}-
    #       ${{ env.CACHE_EPOCH }}-webpack-

    - name: Install
      shell: bash
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: doit setup:js

    - name: Build (js)
      shell: bash
      run: doit -n4 build:js* || doit build:js*

    - name: Build (py)
      shell: bash
      run: doit -n4 build:py*

    - name: Dist
      shell: bash
      run: doit dist
